application: SampleApp
servers:
- hostname: 172.0.0.1
  containers:
  - image: consul-server
    expose: ["8500:8500"]
    variables: ["ENV:production"]
    volumes: ["/data/volume:/data"]
    command: '/bin/bash'
    dockerfile: '/home/user/project/Dockerfile'
  - image: user-management
    count: 2
    links:
    - consul-server
  expose: ["3306:172.0.0.2:3306"]
remote:
  type: s3
  bucket: bucket
  access_key: access
  secret_key: secret
  region: us
  files:
  - name: 'sphinx.tar.bz2'
    path: 'sphinx'
